# The Conda environment specification for {{cookiecutter.project_slug}}
name: {{cookiecutter.project_slug}}
channels:
  - defaults
  - conda-forge
dependencies:
  - python={{cookiecutter.python_version}}
  - pip
  - pip:
# Core pip packages
    - -r requirements.txt
# Linting and development
    - -r requirements_dev.txt